name: "Lint code"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install nodejs dependencies
        run: npm ci

      - name: Start linting
        uses: wearerequired/lint-action@v2
        with:
          eslint: true