name: "Lint code"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start linting
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master